variable "resource_group_name" {}
variable "resource_group_id" {}
variable "location" {}
variable "kv_name" {}
variable "st_name" {}
variable "ai_services_name" {}
variable "ai_foundry_name" {}
variable "ai_foundry_project_name" {}
variable "bing_account_name" {}
variable "tenant_id" {}
variable "subscription_id" {}
variable "current_principal_object_id" {}
variable "aihub_principal_id" {}
