variable "resource_group_name" {}
variable "resource_group_id" {}
variable "location" {}
variable "content_safety_name" {}
variable "cognitive_services_name" {}
variable "speech_name" {}
variable "vision_name" {}
variable "vision_location" {}
variable "bing_name" {}
variable "deploy_bing" {}
variable "content_safety_storage_resource_id" {}
variable "content_safety_location" {}
