variable "resource_group_name" {}
variable "location" {}
variable "azopenai_name" {}
variable "principal_id" {}
variable "allowed_ips" {}
variable "vnet_id" {}
variable "vnet_location" {}
variable "private_endpoints_subnet_id" {}
variable "use_private_endpoints" {}
