variable "resource_group_id" {}
variable "location" {}
variable "ca_name" {}
variable "cae_id" {}
variable "managed_identity_id" {}
variable "managed_identity_client_id" {}
variable "tenant_id" {}
variable "image_name" {}
variable "storage_account_name" {}
variable "storage_container_name" {}
variable "search_service_name" {}
variable "search_index_name" {}
variable "chat_gpt_deployment" {}
variable "chat_gpt_model" {}
variable "embeddings_deployment" {}
variable "embeddings_model" {}
variable "openai_endpoint" {}

variable "enable_entra_id_authentication" {}
