variable "resource_group_name" {}
variable "resource_group_id" {}
variable "location" {}
variable "func_name" {}
variable "image_name" {}
variable "cae_id" {}
variable "cae_default_domain" {}
variable "appi_instrumentation_key" {}
variable "openai_key" {}
variable "openai_model" {}
variable "openai_endpoint" {}
variable "bing_endpoint" {}
variable "bing_key" {}