name: Deploy to Azure

on:
  push:
    branches:
      - dev
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CONTAINERAPP_NAME: ${{ vars.AZURE_CONTAINERAPPS_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Show image name
        run: |
          echo "Imagen: " ${{ env.REGISTRY }}/${{env.IMAGE_NAME}}:2.0.19
      - name: Verify that the image is in ACR
        run: |
          az acr repository show --name ${{ env.REGISTRY }} --image ${{env.IMAGE_NAME}}:2.0.19
      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name ${{env.CONTAINERAPP_NAME}} \
            --resource-group ${{vars.AZURE_RG}} \
            --image ${{ env.REGISTRY }}/${{env.IMAGE_NAME}}:2.0.19

      - name: Verify deployment
        run: |
          az containerapp show \
            --name ${{env.CONTAINERAPP_NAME}} \
            --resource-group ${{vars.AZURE_RG}}
