name: Deploy to Azure

on:
  push:
    branches:
      - dev
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CONTAINERAPP_NAME: ${{ vars.AZURE_CONTAINERAPPS_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Show image name
        run: |
          echo "Imagen: " ${{ env.REGISTRY }}/${{env.IMAGE_NAME}}:2.0.19
      - name: Check if image exists in GHCR
        id: check-image
        run: |
          IMAGE_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" \
          -H "Authorization: Bearer ${{ github.token }}" \
          https://ghcr.io/v2/${{ github.repository_owner }}/aihub/manifests/2.0.19)
          if [ $IMAGE_EXISTS -eq 200 ]; then
            echo "Image exists in GHCR"
          else
            echo "Image does not exist in GHCR"
            exit 1
          fi
      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name ${{env.CONTAINERAPP_NAME}} \
            --resource-group ${{vars.AZURE_RG}} \
            --image ${{ env.REGISTRY }}/${{env.IMAGE_NAME}}:2.0.19

      - name: Verify deployment
        run: |
          az containerapp show \
            --name ${{env.CONTAINERAPP_NAME}} \
            --resource-group ${{vars.AZURE_RG}}
